export const generateMockEvents = () => {
  return [
    {
      id: 'mock1',
      title: 'Coffee & Networking',
      description: 'Join us for a casual coffee meetup! Perfect for making new friends and networking in a relaxed environment.',
      category: 'Social',
      date: 'Dec 20',
      time: '10:00 AM',
      location: 'Starbucks Centro',
      maxAttendees: 8,
      price: 0,
      attendees: ['user1', 'user2', 'user3'],
      creatorId: 'mock_host',
      status: 'published',
      createdAt: new Date().toISOString(),
      compatibilityScore: 92,
    },
    {
      id: 'mock2',
      title: 'Soccer Game at Park',
      description: 'Casual soccer game! All skill levels welcome. Bring water and good vibes.',
      category: 'Sports',
      date: 'Dec 21',
      time: '5:00 PM',
      location: 'Parque Metropolitano',
      maxAttendees: 16,
      price: 0,
      attendees: ['user1', 'user2', 'user3', 'user4', 'user5'],
      creatorId: 'mock_host',
      status: 'published',
      createdAt: new Date().toISOString(),
      compatibilityScore: 85,
    },
    {
      id: 'mock3',
      title: 'Taco Tour Downtown',
      description: 'Let\'s explore the best taco spots in downtown! Walking tour with lots of delicious food.',
      category: 'Food',
      date: 'Dec 22',
      time: '7:00 PM',
      location: 'Centro Histórico',
      maxAttendees: 10,
      price: 150,
      attendees: ['user1', 'user2'],
      creatorId: 'mock_host',
      status: 'published',
      createdAt: new Date().toISOString(),
      compatibilityScore: 78,
    },
    {
      id: 'mock4',
      title: 'Paint & Sip Night',
      description: 'No experience needed! We provide all materials. BYOB and let your creativity flow.',
      category: 'Arts',
      date: 'Dec 23',
      time: '6:30 PM',
      location: 'Art Studio León',
      maxAttendees: 12,
      price: 250,
      attendees: ['user1'],
      creatorId: 'mock_host',
      status: 'published',
      createdAt: new Date().toISOString(),
      compatibilityScore: 88,
    },
    {
      id: 'mock5',
      title: 'Hiking Cerro del Cubilete',
      description: 'Early morning hike to catch the sunrise! Moderate difficulty, amazing views.',
      category: 'Adventure',
      date: 'Dec 24',
      time: '6:00 AM',
      location: 'Cerro del Cubilete',
      maxAttendees: 15,
      price: 0,
      attendees: ['user1', 'user2', 'user3', 'user4'],
      creatorId: 'mock_host',
      status: 'published',
      createdAt: new Date().toISOString(),
      compatibilityScore: 95,
    },
    {
      id: 'mock6',
      title: 'Board Game Night',
      description: 'Bring your favorite board games or try new ones! Pizza and snacks provided.',
      category: 'Social',
      date: 'Dec 25',
      time: '8:00 PM',
      location: 'Game Café León',
      maxAttendees: 12,
      price: 100,
      attendees: ['user1', 'user2', 'user3', 'user4', 'user5', 'user6'],
      creatorId: 'mock_host',
      status: 'published',
      createdAt: new Date().toISOString(),
      compatibilityScore: 91,
    },
    {
      id: 'mock7',
      title: 'Spanish Language Exchange',
      description: 'Practice Spanish & English! Fun conversation topics and cultural exchange.',
      category: 'Learning',
      date: 'Dec 26',
      time: '4:00 PM',
      location: 'Café Literario',
      maxAttendees: 8,
      price: 0,
      attendees: ['user1', 'user2'],
      creatorId: 'mock_host',
      status: 'published',
      createdAt: new Date().toISOString(),
      compatibilityScore: 82,
    },
    {
      id: 'mock8',
      title: 'Photography Walk',
      description: 'Explore the city through your lens! Tips for beginner photographers.',
      category: 'Arts',
      date: 'Dec 27',
      time: '9:00 AM',
      location: 'Zona Piel',
      maxAttendees: 10,
      price: 0,
      attendees: ['user1', 'user2', 'user3'],
      creatorId: 'mock_host',
      status: 'published',
      createdAt: new Date().toISOString(),
      compatibilityScore: 87,
    },
  ];
};
