export const mockEvents = [
  {
    id: '1',
    title: 'Wine Tasting & Cheese Pairing',
    description: 'Join us for an elegant evening of wine and cheese. A sommelier will guide us through 5 wines paired with artisan cheeses.',
    category: 'Food & Drink',
    date: '2025-11-20T19:00:00',
    duration: '2 hours',
    location: 'Centro Histórico, Guadalajara',
    price: 450,
    maxAttendees: 8,
    currentAttendees: 5,
    hostName: 'María García',
    hostAvatar: '🍷',
    language: ['Spanish', 'English'],
    whatsIncluded: ['5 wines', 'Cheese board', 'Sommelier guidance'],
    compatibilityScore: 92,
  },
  {
    id: '2',
    title: 'Sunset Hiking at Barranca',
    description: 'Easy-moderate hike with stunning sunset views. Perfect for nature lovers and photographers.',
    category: 'Outdoors',
    date: '2025-11-18T17:00:00',
    duration: '3 hours',
    location: 'Barranca de Huentitán',
    price: 0,
    maxAttendees: 12,
    currentAttendees: 8,
    hostName: 'Carlos Méndez',
    hostAvatar: '🥾',
    language: ['Spanish'],
    whatsIncluded: ['Trail guide', 'Safety briefing', 'Photography tips'],
    compatibilityScore: 85,
  },
  {
    id: '3',
    title: 'Salsa Dancing for Beginners',
    description: 'Learn basic salsa steps in a fun, judgment-free environment. No partner needed!',
    category: 'Arts & Culture',
    date: '2025-11-19T20:00:00',
    duration: '1.5 hours',
    location: 'Chapultepec, Guadalajara',
    price: 200,
    maxAttendees: 16,
    currentAttendees: 12,
    hostName: 'Ana Rodríguez',
    hostAvatar: '💃',
    language: ['Spanish', 'English'],
    whatsIncluded: ['Dance instruction', 'Practice session', 'Music playlist'],
    compatibilityScore: 78,
  },
  {
    id: '4',
    title: 'Coffee & Board Games Brunch',
    description: 'Casual Sunday brunch with board games. Great for introverts who love strategy games!',
    category: 'Social',
    date: '2025-11-17T11:00:00',
    duration: '2.5 hours',
    location: 'Providencia, Guadalajara',
    price: 150,
    maxAttendees: 8,
    currentAttendees: 4,
    hostName: 'Diego Torres',
    hostAvatar: '☕',
    language: ['Spanish', 'English'],
    whatsIncluded: ['Coffee/tea', 'Light breakfast', 'Board games'],
    compatibilityScore: 95,
  },
  {
    id: '5',
    title: 'Cooking Class: Traditional Tacos',
    description: 'Learn to make authentic Jalisco-style tacos from a local chef. Hands-on experience!',
    category: 'Food & Drink',
    date: '2025-11-21T18:00:00',
    duration: '3 hours',
    location: 'Tlaquepaque',
    price: 550,
    maxAttendees: 10,
    currentAttendees: 7,
    hostName: 'Chef Luis Ramírez',
    hostAvatar: '👨‍🍳',
    language: ['Spanish'],
    whatsIncluded: ['Ingredients', 'Chef instruction', 'Dinner included', 'Recipe cards'],
    compatibilityScore: 88,
  },
  {
    id: '6',
    title: 'Book Club: Contemporary Mexican Literature',
    description: 'Monthly book discussion over coffee. This month: "Signs Preceding the End of the World"',
    category: 'Learning',
    date: '2025-11-22T18:30:00',
    duration: '2 hours',
    location: 'Centro, Guadalajara',
    price: 0,
    maxAttendees: 12,
    currentAttendees: 9,
    hostName: 'Lucía Fernández',
    hostAvatar: '📚',
    language: ['Spanish', 'English'],
    whatsIncluded: ['Coffee', 'Discussion guide'],
    compatibilityScore: 82,
  },
  {
    id: '7',
    title: 'Photography Walk: Street Art',
    description: 'Explore Guadalajara\'s vibrant street art scene. Beginners welcome!',
    category: 'Arts & Culture',
    date: '2025-11-23T10:00:00',
    duration: '2.5 hours',
    location: 'Various locations',
    price: 100,
    maxAttendees: 10,
    currentAttendees: 6,
    hostName: 'Roberto Silva',
    hostAvatar: '📷',
    language: ['Spanish', 'English'],
    whatsIncluded: ['Photography tips', 'Location guide'],
    compatibilityScore: 90,
  },
  {
    id: '8',
    title: 'Yoga & Meditation in the Park',
    description: 'Start your Sunday with gentle yoga and guided meditation. All levels welcome.',
    category: 'Wellness',
    date: '2025-11-24T08:00:00',
    duration: '1.5 hours',
    location: 'Parque Metropolitano',
    price: 0,
    maxAttendees: 20,
    currentAttendees: 15,
    hostName: 'Patricia Gómez',
    hostAvatar: '🧘',
    language: ['Spanish'],
    whatsIncluded: ['Yoga mat', 'Guided session'],
    compatibilityScore: 87,
  },
];

export const categories = [
  'All',
  'Food & Drink',
  'Outdoors',
  'Arts & Culture',
  'Social',
  'Learning',
  'Wellness',
];
